// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_WihQd2KM1yHijEfS0RfYeiduJwKWb30',
    appId: '1:787853588740:web:82950b1e65e10cf8117851',
    messagingSenderId: '787853588740',
    projectId: 'ok-edu-kz',
    authDomain: 'ok-edu-kz.firebaseapp.com',
    storageBucket: 'ok-edu-kz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPNOSbt93y6xl05b4099bynYqk_39tyMw',
    appId: '1:787853588740:android:953b59ec575785b7117851',
    messagingSenderId: '787853588740',
    projectId: 'ok-edu-kz',
    storageBucket: 'ok-edu-kz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZz9FZcb8oLgHYGYlABspuk_8PFW9REIk',
    appId: '1:787853588740:ios:95f8925f06153bc5117851',
    messagingSenderId: '787853588740',
    projectId: 'ok-edu-kz',
    storageBucket: 'ok-edu-kz.appspot.com',
    iosClientId: '787853588740-9h2sdhiehgir6021qnfd39pt52pbhu0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.okEdusKz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZz9FZcb8oLgHYGYlABspuk_8PFW9REIk',
    appId: '1:787853588740:ios:2c6d35fe69879094117851',
    messagingSenderId: '787853588740',
    projectId: 'ok-edu-kz',
    storageBucket: 'ok-edu-kz.appspot.com',
    iosClientId: '787853588740-fa5i4e2h7ucvock63v7lqvu2d9loimke.apps.googleusercontent.com',
    iosBundleId: 'com.example.okEdusKz.RunnerTests',
  );
}
